### ISSUE TITLE
API Key Authentication

### ISSUE THREAD

**Issue by thi-baut** [zacs/ha-gtfs-rt#8]
Hi, I can't authenticate using an API key header, my GTFS provider requires the header to be "apikey" (vs "api_key"), I'm not sure what's the standard. Is there a workaround? The provider: https://developpeurs.stm.info/documentation/gtfsrtv2

**Comment by nips1900** [comment]
Hi,
did you find a way to make it work?
I live in montreal too and i will love to have real time traffic in my home assistant.

**Comment by thi-baut** [comment]
Fork and remove the _ in [this python file](https://github.com/zacs/ha-gtfs-rt/blob/master/custom_components/gtfs_rt/sensor.py), I'm not using this anymore so not sure if it still works

**Comment by thi-baut** [comment]
I updated the code to support the STM, see https://github.com/zacs/ha-gtfs-rt/pull/14

**Comment by nips1900** [comment]
Thank you so much!

**Comment by zacs** [comment]
Fixed in #14 -- thank you @thi-baut !
